services:
  qdrant:
    image: qdrant/qdrant:latest
    ports:
      - "6333:6333"
    volumes:
      - ./long_term_memory:/qdrant/storage
    restart: unless-stopped
  api:
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "8080:8080"
    env_file:
      - .env
    environment:
      - QDRANT_PORT=6333
      - QDRANT_API_KEY=None
      - QDRANT_HOST=localhost
      - QDRANT_URL=http://qdrant:6333
      - MONGO_URI=${MONGO_URI}
    restart: unless-stopped
    volumes: 
      - ./short_term_memory:/app/data
    depends_on:
      - qdrant