services:
  traefik:
    image: traefik:v3.6
    command:
      - "--log.level=DEBUG"
      - "--api.insecure=false"
      - "--providers.docker=true"
      - "--providers.docker.exposedbydefault=false"
      - "--entrypoints.web.address=:80"
      - "--entrypoints.web.http.redirections.entryPoint.to=websecure"
      - "--entrypoints.web.http.redirections.entryPoint.scheme=https"
      - "--entrypoints.websecure.address=:443"
      - "--certificatesresolvers.myresolver.acme.dnschallenge=true"
      - "--certificatesresolvers.myresolver.acme.dnschallenge.provider=cloudflare"
      - "--certificatesresolvers.myresolver.acme.email=${ACME_EMAIL}"
      - "--certificatesresolvers.myresolver.acme.storage=/letsencrypt/acme.json"
    environment:
      - CF_DNS_API_TOKEN=${CF_DNS_API_TOKEN}
    ports:
      - "80:80"
      - "443:443"
    volumes:
      - "/var/run/docker.sock:/var/run/docker.sock:ro"
      - "./letsencrypt:/letsencrypt"
    restart: unless-stopped

  api:
    image: ghcr.io/maxwell-tchiabe/sparring-partner-api:${IMAGE_TAG:-staging}
    env_file:
      - .env
    restart: unless-stopped
    volumes:
      - ./short_term_memory:/app/data
    labels:
      - "traefik.enable=true"
      # General API Router
      - "traefik.http.routers.api.rule=Host(`${DOMAIN_NAME}`)"
      - "traefik.http.routers.api.entrypoints=websecure"
      - "traefik.http.routers.api.tls.certresolver=myresolver"
      - "traefik.http.routers.api.middlewares=api-ratelimit"

      # General API Rate Limit: 100 requests per minute, burst of 50
      - "traefik.http.middlewares.api-ratelimit.ratelimit.average=5"
      - "traefik.http.middlewares.api-ratelimit.ratelimit.period=1m"
      - "traefik.http.middlewares.api-ratelimit.ratelimit.burst=5"

      # Chat Specific Router (protect resource)
      - "traefik.http.routers.api-chat.rule=Host(`${DOMAIN_NAME}`) && Path(`/api/chat`)"
      - "traefik.http.routers.api-chat.entrypoints=websecure"
      - "traefik.http.routers.api-chat.tls.certresolver=myresolver"
      - "traefik.http.routers.api-chat.middlewares=chat-ratelimit"
      - "traefik.http.routers.api-chat.priority=100"
      - "traefik.http.routers.api-chat.service=api" # REQUIRED: point to the api backend service

      # Chat Specific Rate Limit: 10 requests per minute, burst of 5
      - "traefik.http.middlewares.chat-ratelimit.ratelimit.average=1"
      - "traefik.http.middlewares.chat-ratelimit.ratelimit.period=1h"
      - "traefik.http.middlewares.chat-ratelimit.ratelimit.burst=2"

      - "traefik.http.services.api.loadbalancer.server.port=8080"
