'use client';

import { LegalLayout } from '@/components/layout/LegalLayout';

export default function TermsPage() {
  return (
    <LegalLayout 
      title="Terms of Service" 
      subtitle="Standard usage protocol and cognitive interface agreement for the EvoChat ecosystem."
      lastUpdated="April 2026"
    >
      <section>
        <h2>1. Scope of Application</h2>
        <p>
          These Terms of Service apply to all users of the EvoChat platform. By accessing our cognitive interface, you agree to comply with these regulations.
        </p>
      </section>

      <section>
        <h2>2. Service Description</h2>
        <p>
          EvoChat provides an AI-powered language sparring partner. The service includes real-time voice chat, text analysis, and cognitive memory tracking. 
        </p>
      </section>

      <section>
        <h2>3. User Responsibilities</h2>
        <p>
          You are responsible for maintaining the confidentiality of your account credentials. You agree not to use the service for any illegal purposes or to transmit harmful data.
        </p>
      </section>

      <section>
        <h2>4. Data Sovereignty</h2>
        <p>
          While EvoChat analyzes your learning patterns to improve your experience, you remain the owner of your personal data. You can delete your session history and account at any time.
        </p>
      </section>

      <section>
        <h2>5. Limitation of Liability</h2>
        <p>
          EvoChat is an AI-driven educational tool. While we strive for absolute accuracy, we are not liable for linguistic errors or misunderstandings generated by the AI models.
        </p>
      </section>

      <section>
        <h2>6. Termination</h2>
        <p>
          We reserve the right to suspend accounts that violate our usage protocol or engage in fraudulent activities.
        </p>
      </section>
    </LegalLayout>
  );
}
